# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documentos', '0003_auto_20160613_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
