# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 02:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0006_auto_20160615_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
