# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0009_auto_20160616_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoxprofesor',
            name='area',
        ),
        migrations.AddField(
            model_name='cursoxprofesor',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Profesor'),
        ),
    ]
