# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0010_auto_20160616_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoxprofesor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='cursoxprofesor',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='cursoxprofesor',
        ),
        migrations.AddField(
            model_name='archivo',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.curso'),
        ),
        migrations.DeleteModel(
            name='cursoxprofesor',
        ),
    ]
