# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documentos', '0012_auto_20160616_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='archivo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
