# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0015_auto_20160618_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Area'),
        ),
    ]
