# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0017_archivo_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='votos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
