# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0018_auto_20160618_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('archivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Archivo')),
            ],
        ),
    ]
