# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 00:32
from __future__ import unicode_literals

import Documentos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0020_auto_20160624_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(null=True, upload_to='documentos/', validators=[Documentos.validators.valid_extension]),
        ),
    ]
