# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-03 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0025_votante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='archivo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='archivo',
            field=models.ManyToManyField(to='Documentos.Archivo'),
        ),
    ]
