# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0027_auto_20160703_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='archivo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='profesor',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Profesor'),
        ),
    ]
