# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0028_auto_20160704_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='coment',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='profesor',
        ),
        migrations.AddField(
            model_name='comentario',
            name='profe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='coment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Comentario'),
        ),
    ]
