# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0029_auto_20160704_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='profe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Profesor'),
        ),
    ]
