# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0030_auto_20160704_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='coment',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='coment',
            new_name='Comentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='profe',
        ),
        migrations.AddField(
            model_name='comentario',
            name='Profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Profesor'),
        ),
    ]
