# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20160605_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Provincia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Departamento'),
        ),
    ]
