# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20160605_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.Distrito'),
        ),
    ]
