# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alumno_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eap', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='eap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.EAP'),
        ),
    ]
