# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_auto_20160629_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='myfolder/'),
        ),
    ]
